name: firebase_crud_example
description: An example to show crud operations in firebase

#compiled with Flutter 1.25.0-8.2.pre • channel beta
#Framework • revision b0a2299859
#Engine • revision 92ae191c17
#Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)

version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_core:
  auto_size_text: ^2.1.0
  visibility_detector: ^0.1.5
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/